version: '3.8'
services:
  api-gateway:
    build: ./backend/gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your_jwt_secret_key
      - AUTH_SERVICE_URL=http://auth-service:3000
      - CHALLENGE_SERVICE_URL=http://challenge-service:3000
      - EXECUTION_SERVICE_URL=http://execution-service:3000
    depends_on:
      - auth-service
      - challenge-service
      - execution-service

  auth-service:
    build: ./backend/services/auth-service
    ports:
      - "3001:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/auth
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=90d
    depends_on:
      - mongodb
      - redis

  challenge-service:
    build: ./backend/services/challenge-service
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/challenges
      - AUTH_SERVICE_URL=http://auth-service:3000
    depends_on:
      - mongodb
      - auth-service

  execution-service:
    build: ./backend/services/execution-service
    privileged: true
    environment:
      - MAX_EXECUTION_TIME=5000
      - MAX_MEMORY=100M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
  redis_data: 