version: '3.8'

services:
  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/auth
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRES_IN=90d
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  challenge-service:
    build: ./services/challenge-service
    ports:
      - "3002:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/challenges
      - AUTH_SERVICE_URL=http://auth-service:3000
      - EXECUTION_SERVICE_URL=http://execution-service:3000
    depends_on:
      - mongodb
      - auth-service

  execution-service:
    build: ./services/execution-service
    ports:
      - "3003:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/execution
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongodb

  community-service:
    build: ./services/community-service
    ports:
      - "3004:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/community
      - AUTH_SERVICE_URL=http://auth-service:3000
    depends_on:
      - mongodb
      - auth-service

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  monitoring:
    build: ./services/monitoring-service
    ports:
      - "3005:3000"
    depends_on:
      - auth-service
      - challenge-service
      - execution-service
      - community-service

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    volumes:
      - ../:/usr/src/frontend
      - ./gateway:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - AUTH_SERVICE_URL=http://auth-service:3000
      - CHALLENGE_SERVICE_URL=http://challenge-service:3000
      - EXECUTION_SERVICE_URL=http://execution-service:3000
      - COMMUNITY_SERVICE_URL=http://community-service:3000
      - FRONTEND_PATH=/usr/src/frontend
    depends_on:
      - auth-service
      - challenge-service
      - execution-service
      - community-service

volumes:
  mongodb_data:
  redis_data: