version: '3.8'

services:
  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/auth
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRES_IN=90d
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  challenge-service:
    build: ./services/challenge-service
    ports:
      - "3002:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/challenges
      - AUTH_SERVICE_URL=http://auth-service:3000
      - EXECUTION_SERVICE_URL=http://execution-service:3000
    depends_on:
      - mongodb
      - auth-service

volumes:
  mongodb_data: 